site_name: OWASP Nettacker Documentation
theme:
  name: material
nav:
  - Home: Home.md
  - Installation: Installation.md
  - Usage: Usage.md
  - Codebase Overview: CodebaseOverview.md
  - Modules: Modules.md
  - API: API.md
  - Contributing: Developers.md
  - Contributors: Contributors.md
  - Media: Media.md
  - Events: Events.md
